### ISSUE TITLE
Dependency can not resolve

### ISSUE THREAD

**Issue by hendisantika** [piomin/sample-spring-data-webflux#1]
Very nice tutorial & sample.

But, I can't download the dependencies about r2jbc.
```
[ERROR] Failed to execute goal on project employee-service: Could not resolve dependencies for project pl.piomin.service:employee-service:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.springframework.data:spring-data-jdbc:jar:1.0.0.r2dbc-SNAPSHOT, io.r2dbc:r2dbc-spi:jar:1.0.0.M5, io.r2dbc:r2dbc-postgresql:jar:1.0.0.M5: Could not find artifact org.springframework.data:spring-data-jdbc:jar:1.0.0.r2dbc-SNAPSHOT
```

Any suggestion?

Thanks

**Comment by hendisantika** [comment]
Hi, @piomin. I already read your article again. And I still can't find the required libs that I should add it into pom.xml. 

It's only written : 
```
<dependency>

    <groupId>org.springframework.boot</groupId>

    <artifactId>spring-boot-starter-webflux</artifactId>

</dependency>

<dependency>

    <groupId>org.springframework.data</groupId>

    <artifactId>spring-data-jdbc</artifactId>

    <version>1.0.0.r2dbc-SNAPSHOT</version>

</dependency>

<dependency>

    <groupId>io.r2dbc</groupId>

    <artifactId>r2dbc-spi</artifactId>

    <version>1.0.0.M5</version>

</dependency>

<dependency>

    <groupId>io.r2dbc</groupId>

    <artifactId>r2dbc-postgresql</artifactId>

    <version>1.0.0.M5</version>

</dependency>
```
and
```
<dependencyManagement>

    <dependencies>

        <dependency>

            <groupId>org.springframework.data</groupId>

            <artifactId>spring-data-releasetrain</artifactId>

            <version>Lovelace-RELEASE</version>

            <scope>import</scope>

            <type>pom</type>

        </dependency>

    </dependencies>

</dependencyManagement>
```

CMIIW.

**Comment by piomin** [comment]
Yes, you are right. Sorry. We need some repositories with spring milestones
ans snapshots. Here are addresses
https://github.com/r2dbc/r2dbc-postgresql/blob/master/README.md

**Comment by hendisantika** [comment]
I didn't know Why I still can't download the required dependencies. Even I already added the required libs.

Any suggestion?

**Comment by hendisantika** [comment]
I tried clone your repo, but also can run the project : 
```
mvn clean package
```

Here the errors :
```
[ERROR] Failed to execute goal on project employee-service: Could not resolve dependencies for project pl.piomin.service:employee-service:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: io.r2dbc:r2dbc-spi:jar:1.0.0.M5, io.r2dbc:r2dbc-postgresql:jar:1.0.0.M5: Could not find artifact io.r2dbc:r2dbc-spi:jar:1.0.0.M5 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

Any suggestions?

Thanks

**Comment by valekar** [comment]
This link https://github.com/r2dbc/r2dbc-postgresql/blob/master/README.md helped me
I added repositories in my maven file and found maven was able to download the libraries
 <repositories>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

**Comment by piomin** [comment]
i updated it to the latest version
